---
title: "Tidy Tuesday 2"
description: "Second Tidy Tuesday assignments for Advanced Data Science in R"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message=FALSE, warning=FALSE, error = TRUE)

library(tidyverse) 
library(ggplot2)
library(RColorBrewer)
library(extrafont)
```

```{r}
nominees_tt <- read_csv("C:/Users/kates/OneDrive/Desktop/Advanced_data_science/TidyTuesday/nominees_tt.csv")
```
```{r}
#unique(nominees_tt$distributor) # how to see all different variables 

nominees_tt %>%
  select(type,
         title,
         distributor,
         year) %>%
  filter(distributor == c('Hulu', 
                          'HBO Max', 
                          'Netflix',
                          'HBO',
                          'Disney+',
                          'Showtime', 
                          
                          'Peacock')) %>%
  group_by(distributor, 
           type) %>%
  mutate(Count = n()) %>%
  ggplot(aes(x = distributor, fill = type)) + 
  geom_bar() + 
  labs(title = "Nominations and Win Totals by Top 7 Streaming Services from 1957 - 2021", 
       x = "Distributor", 
       y = "") + 
  guides(fill = guide_legend(title = NULL)) + 
  theme_minimal() 

```

```{r}
nominees_tt %>%
  select(type,
         title,
         distributor,
         year) %>%
  filter(type == "Winner")%>%
  filter(distributor == c('Hulu', 
                          'HBO Max', 
                          'Netflix',
                          'HBO',
                          'Disney+',
                          'Showtime',
                          'Prime Video',
                          'Peacock')) %>%
  group_by(year, distributor) %>%
  mutate(Count = n()) %>%
  ggplot(aes(x = year, y = Count, color = distributor)) + 
  geom_point() + 
  theme_minimal() + 
  labs(title = "Emmy Win Totals by Top 6 Streaming Services from 1995 - 2021", 
       x = "", 
       y = "") + 
  guides(fill = guide_legend(title = NULL))+ 
  theme(panel.grid.major.x = element_blank(), 
        plot.title = element_text(family = "A", hjust = 0.5))
```


```{r}
windowsFonts(A = windowsFont("Times New Roman"))

nominees_10 <- nominees_tt %>%
  filter(year >2000)


nominees_10 %>%
  mutate(year = as.factor(year)) %>%
  select(type,
         title,
         distributor,
         year) %>%
  filter(type == "Winner")%>%
  filter(distributor == c('Hulu', 
                          'HBO Max', 
                          'Netflix',
                          'HBO',
                          'Disney+',
                          'Showtime',
                          'Prime Video',
                          'Peacock')) %>%
  group_by(year, distributor) %>%
  mutate(Count = n()) %>%
  ggplot(aes(x = year, fill = distributor)) + 
  geom_bar(position = "stack") + 
  theme_minimal() + 
  scale_fill_brewer(palette = "Set2") + 
  labs(title = "Emmy Win Totals by Top 6 Streaming Services from 2000 - 2021", 
       x = "", 
       y = "") + 
  guides(fill = guide_legend(title = NULL))+ 
  theme(panel.grid.major.x = element_blank(), 
        plot.title = element_text(family = "A", hjust = 0.5))
```

